name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # This makes the token available to the shell session
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 0: Git Authentication
      - name: Configure git authentication
        run: |
          git config --global url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"      

      # Step 1: Install dependencies using requirements.txt to catch --find-links
      #- name: Install dependencies from requirements => NOT RECOMMENDED
      #  run: |
      #    # We rewrite the URL on the fly using the token
      #    pip install --find-links https://x-access-token:${GH_TOKEN}@github.com/hgmuc/basic_helpers/releases -r requirements.txt

      # Step 2: Install geom_helpers and its dev tools
      # Note: We keep this to ensure all [dev] and [typecheck] tools are present
      - name: Install package in editable mode
        run: pip install -e .[dev,typecheck] --no-deps

      # Step 3: Run your tests
      - name: Run tests
        run: pytest

      # Step 4: Run type checking
      - name: Run static analysis
        run: mypy src/
